name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25']
    steps:
    - name: Checkout armature-iam
      uses: actions/checkout@v4
      with:
        path: armature-iam
    - name: Checkout httpauthshim
      uses: actions/checkout@v4
      with:
        repository: jamesread/httpauthshim
        path: httpauthshim
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      working-directory: armature-iam
      run: go mod download
    - name: Install gocyclo
      run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v9.2.0
      with:
        version: latest
        working-directory: armature-iam
    - name: Run tests
      working-directory: armature-iam
      run: make test
    - name: Check code complexity
      working-directory: armature-iam
      run: make gocyclo
    - name: Run linter
      working-directory: armature-iam
      run: make golangci
